# Generated by Django 4.1.2 on 2022-10-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstatus',
            old_name='name',
            new_name='status',
        ),
    ]
