# Generated by Django 4.1.2 on 2022-10-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
