# Generated by Django 4.1.2 on 2022-10-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_alter_client_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, validators=[events.validators.validate_support_contact]),
        ),
    ]
